version: "3.8"  # Add this if required by your Docker Compose version

services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
