spring:
  application:
    name: netquest-backend
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://vsgate-s1.dei.isep.ipp.pt:10406/netquest
    username: root
    password: htLD7J9wkLaS

app:
  cors:
    allowed-origins: http://localhost:3000, https://netquest-dev-environment.onrender.com, https://netquest-labdsof-prod.onrender.com

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
