name: Deploy Development App
on:
  workflow_dispatch:
jobs:
  pipeline:
    name: NetQuest general pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 20.12.2
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Install Node.js packages
        working-directory: ./netquest-frontend
        run: npm install
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_REPO }}:dev .
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_REPO }}:dev
      - name: Webhook for render deployment
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.RENDER_WEBHOOK }}
